XV. Jetpack Compose
ZFRFM/SimbirSoftPractice pull request #19
Opened 2024-07-30 08:06 UTC by ZFRFM

2024-07-30 09:24 UTC, Arantier requested changes

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +        },
Вот тут всё правильно, но заметь - у тебя нет консистентности. Ты слишком торопливый и невнимательный. Со временем это пройдёт, но скорее всего уже когда ты на чём-то обожжёшься. Попробуй не допустить этого и начать работать раньше над своими проблемами

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +    )
Цвета не из темы

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +                val description = if (passwordHidden) "Show password" else "Hide password"
"О нет, что же тут написано? Почему разработчик не думает обо мне, простом юзере из Усть-Подпердолинска, который хочет заняться благотворительностью, но не знает английский язык? Почему ему плевать на нас?"

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +    var passwordHidden by rememberSaveable { mutableStateOf(true) }
Когда у тебя в руках молоток всё выглядит как гвоздь, но ты уверен, что `rememberSaveable` тут удачная опция? Тебе не все состояния нужно сохранять в бандлы и более того, стоит думать о том, когда стоит это делать не надо т.к. лишние записи в бандл - лишняя нагрузка от твоего приложения

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +                color = colorResource(id = R.color.black_38),
Цвета не из темы

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +                    IconButton(onClick = { backPressed.invoke() }) {
```suggestion
                    IconButton(onClick = backPressed) {
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +                            tint = colorResource(id = R.color.white),
Цвета не из темы

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +                modifier
```suggestion
                Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +            textAlign = TextAlign.Center,
В типографию. Кстати, опять же про отсутствие консистентности - тут ты используешь Color.White, а не R.color.white, что правильно, но намекает на проблему

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +) {
Всё то же, что и выше, про хойстинг, порядок параметров и саппрессы

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                modifier = modifier,
```suggestion
                modifier = Modifier,
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                modifier
```suggestion
                Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +    Scaffold(
```suggestion
    Scaffold(
        modifier = modifier,
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                    .background(color = colorResource(id = R.color.light_grey_two))
Цвета не из темы

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                    .padding(horizontal = 8.dp),
Неправильный порядок модификаторов. У тебя innerPadding перепишет horizontal. Рекомендую начать запоминать то, как работает порядок модификаторов: https://zsmb.co/remembering-modifier-order/

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                Spacer(modifier = modifier.height(8.dp))
```suggestion
                Spacer(modifier = Modifier.height(8.dp))
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                NewsItem(
А тут где модифаер? Я бы ожидал хотя бы `Modifier.fillMaxWidth()`

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +    modifier: Modifier = Modifier,
Порядок, саппресс

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                modifier = modifier,
```suggestion
                modifier = Modifier,
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                    modifier
```suggestion
                    Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                fontFamily = FontFamily(Font(R.font.officina_sans_extra_bold_c)),
Цвета и типографию в тему

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                modifier
```suggestion
                Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                modifier
```suggestion
                Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                    ),
Просто сахар для читаемости
```suggestion
                    .padding(top = 10.dp, bottom = 16.dp)
                    .padding(horizontal = 24.dp),
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                Modifier
\`\`\`suggestion Modif... А нет погодите-ка... Замечаешь неконсистентность?

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                fontSize = 12.sp,
Цвета и типографию в тему

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +) {
Суппресс, порядок параметров и ещё нейминг - ты же думаешь, что у тебя будет всего один TopAppBar в приложении?

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +) {
Тут тоже забыл отметиться по суппрессу, порядку и неймингу

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +    Box {
Коробка. А зачем?

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/TopAppBar.kt
> +    Box {
И тут та же история

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +                    containerColor = colorResource(id = R.color.leaf),
В тему

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +            title = { },
Может лучше текст снизу сюда переместить? Или тебя мучает баг с двойным заголовком?

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +                            tint = colorResource(id = R.color.white),
В тему

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +                modifier
```suggestion
                Modifier
```

2024-07-30 09:24 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/TopAppBar.kt
> +        )
Цвета  и типографию в тему

2024-07-31 12:02 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                modifier
Думал сразу к modifier прицепить и innerPadding. Исправлено

2024-07-31 12:38 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +            Spacer(modifier = modifier.height(40.dp))
всё пойдёт в тартарары

2024-07-31 12:53 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                    modifier
Согласен, Я его поправляю, шаг в сторону и линтер его сносит...

2024-07-31 13:05 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/EmailTextField.kt
> +        modifier = modifier.fillMaxWidth(),
Натыкал их "на всякий случай" ахах. Исправлено

2024-07-31 13:13 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +@Suppress("ktlint:standard:function-naming")
Устал( Сразу после модификаторов прочитаю как исправить линтер

2024-07-31 13:22 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +                val description = if (passwordHidden) "Show password" else "Hide password"
Так ещё и хардкодовый текст... не знаю под чем Я был когда это писал ахах

2024-07-31 13:28 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
> +    var passwordHidden by rememberSaveable { mutableStateOf(true) }
Ну собсна а почему бы не сохранять видимость пароля в бандле? Иначе говоря, где его ещё можно сохранить, если за рамки экрана и конфигурации это не выходит? Ну и remember не подходит -> пользователь ввёл невидимый пароль, перевернул экран, а пароль уже читабельный...

2024-07-31 13:51 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                    ),
к такому коду Я и стремлюсь)

2024-07-31 13:53 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                Modifier
это походу тот самый Modifier, который должен был быть "ошибкой", но по итогу единственный правильный

2024-07-31 16:18 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                    .background(colorResource(id = R.color.white))
Тут Я честно говоря, наоборот старался больше использовать colorResource, т.к. часто видел подобное в кодлабах гугла. Ошибку понял.
Закинул несколько цветов в светлую палитру темы. Кастомные значения цветов задаю прямо из файла Colors. С MaterialTheme очень много тонкостей где какой цвет используется. Для ускорения процесса использую Colors. Скорее всего, некоторые цвета можно и перенести в MaterialTheme

2024-07-31 19:24 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                    color = Color.White,
ну как-то не то задавать тексту цвет MaterialTheme.colorScheme.background... задал просто white из файла, благо в файле цвета все композаблы

2024-08-01 12:06 UTC, Arantier requested changes

2024-08-01 12:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationViewModel.kt
> +    }
Попробуй вернуть, эта штука выглядит уродливо и ей сложнее управлять

2024-08-01 12:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/AuthorizationScreenBase.kt
> +}
Превью могут намного больше, чем просто показывать значения. Заведи тут переменные для имейла и пароля и сымитируй условие, которое стоит на них в более широком плане, передав в `isSignInButtonEnabled = email.isNotEmpty() && password.isNotEmpty()`. Потом запусти интерактивный режим превью и офигей

2024-08-01 12:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/AuthorizationTopAppBar.kt
> +            modifier = Modifier,
Мусор

2024-08-01 12:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/AuthorizationTopAppBar.kt
> +fun findActionBarThemeHeightInDp(): Dp {
Оверкилл, просто ставь 56.дп из зеплина

2024-08-01 12:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsTopAppBar.kt
> +fun findActionBarThemeHeightInDp(): Dp {
Оверкилл, ставь 56.дп

2024-08-02 04:38 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/AuthorizationScreenBase.kt
> +    modifier: Modifier = Modifier,
Это просто к сведению? У меня в коде вроде всё так

2024-08-02 04:45 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +fun AuthorizationScreen(modifier: Modifier = Modifier) {
хмм... это же просто обёртка на AuthorizationScreen для получения состояния. В нём лишь своя composable-ф-я AuthorizationScreen

2024-08-02 04:47 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +    val isSignInButtonEnabledState = authorizationViewModel.isAuthEnabledLiveData.observeAsState()
кажется, некоторые треды были в патче)

2024-08-02 04:53 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/PasswordTextField.kt
>  fun PasswordTextField(
А не получится ли файл на много строк кода? При сложном UI - вполне возможно. На какое ограничение по кол-ву строк в файле ориентироваться?

2024-08-02 05:03 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/NewsScreen.kt
> +                modifier = Modifier,
чтобы не было "блин, а где тут modifier":) убрал

2024-08-02 05:29 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/composeunit/AuthorizationScreenBase.kt
> +}
вау) и почему же xml так медленно уходит)

2024-08-02 08:29 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/models/NewsCompose.kt
> +data class NewsCompose(
Самое главное забыл:
```suggestion
@Immutable
data class NewsCompose(
```
https://developer.android.com/develop/ui/compose/performance/stability/fix#annotate-stable
https://stackoverflow.com/questions/68575936/what-do-the-stable-and-immutable-annotations-mean-in-jetpack-compose

2024-08-02 08:29 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                .fillMaxSize(),
Я имел ввиду только fillMaxSize(). background верни назад

2024-08-02 08:30 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                .fillMaxSize(),
Пойми: композаблы инкапсулируют какую-то логику отображения внутри себя, а какую-то отдают на аутсорс потому что это не их обязанность. Фон является обязанностью экрана, а позиционирование - нет

2024-08-02 09:06 UTC, Arantier requested changes

2024-08-02 09:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                .background(colorResource(id = R.color.white))
![green-mile-im-tired-boss](https://github.com/user-attachments/assets/3cdbed87-45ec-4407-8331-e77a44c8a4b0)

2024-08-02 09:06 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Theme.kt
> +    )
Зачем тебе два типа темы сразу? Это было в задании? Или это просто было в тестовом примере и ты решил не напрягать мозги, чтобы избавиться от лишнего кода? Вопрос риторический.

2024-08-02 09:11 UTC, Arantier requested changes

2024-08-02 09:11 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                modifier = Modifier,
Файми, если я говорю о том, что у тебя в коде есть проблема и она повторяется, ты не должен исправить её только в тех местах, где я указал, а во всём коде. Ещё раз - такое отношение в высшей степени неуважительно к ревьюеру, потому что ты опускаешь человека с уровня напарника до уровня линтера, который пройдётся по твоему сырому коду и покажет на все те косяки, которые тебе было влом фиксить самому. У тебя таких модификаторов в коде ещё 3 штуки. Пожалуйста, догадайся нажать Ctrl+Shift+F и потратить целых 3 минуты на их исправление

2024-08-02 09:34 UTC, Arantier requested changes

2024-08-02 09:34 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +fun NewsItem(
Этот айтем перестал соответствовать дизайну. У него нет элевации и закруглённых краёв. Тебе стоило использовать композабл Card, либо изобрести велосипед с помощью `Modifier.clip(RoundedCornerShape(some.dp))`

2024-08-02 09:34 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +            )
У тебя сломан превью т.к. ты не установил размеры для этого композабла. А раз сломан превью, то и в проде может возникнуть поломка

2024-08-02 09:34 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +    Column(
Этот композабл довольно сложный, согласись? Нужно несколько Box, Column и Row, чтобы наладить его работу. Это неудобно. Используй композабл ConstraintLayout
https://developer.android.com/develop/ui/compose/layouts/constraintlayout

2024-08-02 09:47 UTC, Arantier requested changes

2024-08-02 09:47 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Colors.kt
> +    val orange_badge = Color(0xffFF8400)
Мда, не заметил слона в посудной лавке - откуда ты вообще взял snake_case? Зачем он нам тут?

2024-08-02 09:47 UTC, Arantier commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Typography.kt
> +    val officina_sans_extra_bold_c =
Аналогичный вопрос про snake_case

2024-08-02 18:53 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                .fillMaxSize(),
Запомнил

2024-08-02 18:55 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/models/NewsCompose.kt
> +data class NewsCompose(
впервые встречаю такую аннотацию)

2024-08-02 18:58 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Colors.kt
> +}
Принято. Когда создавал, было размышление "а дай все цвета из ресурсов закину, авось понадобятся"

2024-08-02 19:02 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +                .background(colorResource(id = R.color.white))
видимо colorResource спрятался хорошо (

2024-08-03 03:53 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Theme.kt
> +    )
Это было в тестовом примере) но оставить решил по другой причине, даже цвета переопределил, на случай "расширения" кода. Это тот самый кусочек кода, который в "будущем" точно понадобится

2024-08-03 04:07 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Colors.kt
> +    val orange_badge = Color(0xffFF8400)
Ой, это было что-то вроде Ctrl + C -> Ctrl + V из ресурсов

2024-08-03 04:07 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/theme/Typography.kt
> +    val officina_sans_extra_bold_c =
тоже ресурсы

2024-08-03 07:11 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/authorization/AuthorizationScreen.kt
> +                modifier = Modifier,
Кажется, исправил все

2024-08-03 07:35 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +            )
Конкретных значений этому композаблу задать нельзя, слетает дизайн, экраны разные. Поставил разные fillMax... тоже не помогло. Возможно, для этого компосабла поведение превьюшки и не реализовано, это сторонняя библиотека

2024-08-03 07:38 UTC, ZFRFM commented on app/src/main/java/ru/faimizufarov/simbirtraining/java/presentation/ui/screens/news/composeunit/NewsItem.kt
> +    Column(
обалдеть, и такое есть)

2024-08-05 09:03 UTC, Arantier approved these changes

2024-08-06 08:28 UTC, merged